# Generated by Django 4.0.7 on 2022-09-23 01:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_sender_id', models.PositiveIntegerField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject', models.TextField(verbose_name='Subject')),
                ('html_message', models.TextField(verbose_name='HTML Message')),
                ('plain_message', models.TextField(verbose_name='Plain Message')),
                ('template_name', models.TextField(verbose_name='Template Name')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('E', 'Error')], default='P', max_length=1, verbose_name='Email Status')),
                ('status_message', models.TextField(verbose_name='Status Message')),
                ('queued_date', models.DateTimeField(auto_now_add=True, verbose_name='Queued Date')),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('copy_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='the_emails.email', verbose_name='Copy of')),
                ('sender_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('sub_sender_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_emails', to='contenttypes.contenttype', verbose_name='sub sender')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='the_emails.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('ADMIN', 'Admin'), ('LEGAL', 'Legal'), ('COMPLIANCE', 'Compilance'), ('ACCOUNTS', 'Accounts')], max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Email Groups',
                'unique_together': {('group_name', 'email_id')},
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='attachment', max_length=140, null=True)),
                ('template_name', models.TextField(verbose_name='Template Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_type', models.TextField(verbose_name='Content Type')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='the_emails.email')),
            ],
        ),
    ]
